<?php
/**
* Customer Reviews Slider Template
*
* This template displays customer reviews in a responsive, stylish slider.
*
* @package ctrw
*/

if (!defined('ABSPATH')) {
   exit; // Exit if accessed directly.
}

// Fetch approved reviews from the database model.
$reviews_model = new CTRW_Review_Model();
$reviews = $reviews_model->get_reviews('approved');

// Get plugin settings to determine how many reviews to show.
$settings = get_option('customer_reviews_settings', []);
$reviews_per_page = $settings['reviews_per_page'] ?? 10;
$reviews = array_slice($reviews, 0, $reviews_per_page);
$review_count = count($reviews);
?>
<div class="ctrw-slider-container">


   <div class="ctrw-slider-navigation-wrapper">
       <div class="ctrw-slider-wrapper">
           <div class="ctrw-slider-slides <?php if ($review_count < 3) echo 'center-items'; ?>">
               <?php
               foreach ($reviews as $review) {
                   // Settings for each review
                   $show_city = !empty($settings['show_city']);
                   $date_format_setting = $settings['date_format'] ?? 'MM/DD/YYYY';
                   $formatted_date = '';
                   if (!empty($review->created_at)) {
                       $timestamp = strtotime($review->created_at);
                       $date_format = str_replace(['MM', 'DD', 'YYYY'], ['m', 'd', 'Y'], $date_format_setting);
                       $formatted_date = date($date_format, $timestamp);
                   }
               ?>
               <div class="ctrw-slider-slide">
                   <div class="ctrw-slider-meta">
                  
                       <div class="ctrw-slider-author-info">
                           <div class="ctrw-slider-author-name"><?= esc_html($review->name); ?></div>
                           <div class="ctrw-slider-date"><?= esc_html($formatted_date); ?></div>
                          

                       </div>
                   </div>
                  
                   <div class="ctrw-slider-rating-wrapper">
                       <div class="ctrw-slider-rating" aria-label="Rating: <?php echo (int) $review->rating; ?> out of 5 stars">
                           <?php for ($i = 0; $i < 5; $i++) : ?>
                               <span class="<?php echo $i < $review->rating ? 'filled' : 'empty'; ?>">&#9733;</span>
                           <?php endfor; ?>
                       </div>
                       <svg class="ctrw-verified-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1.41 14.59L6.17 13.17l1.41-1.41L10.59 14.17l5.83-5.83 1.41 1.41-7.24 7.24z"></path></svg>
                   </div>
                  
                   <div class="ctrw-slider-content">
                      <div class="ctrw-review-title"><?= esc_html($review->title); ?></div>
                       <p><?= esc_html($review->comment); ?></p>
                   </div>
               </div>
               <?php } ?>
           </div>
       </div>
   </div>

   <?php if ($review_count > 1): ?>
   <div class="ctrw-slider-controls">
       <button class="ctrw-slider-prev" aria-label="Previous review">&#10094;</button>
       <div class="ctrw-slider-controls-dots">
           <!-- Dots are dynamically generated by JavaScript -->
       </div>
       <button class="ctrw-slider-next" aria-label="Next review">&#10095;</button>
   </div>
   <?php endif; ?>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
   const container = document.querySelector('.ctrw-slider-container');
   if (!container) return;

   const slidesContainer = container.querySelector('.ctrw-slider-slides');
   const slides = container.querySelectorAll('.ctrw-slider-slide');
   const prevButton = container.querySelector('.ctrw-slider-prev');
   const nextButton = container.querySelector('.ctrw-slider-next');
   const dotsContainer = container.querySelector('.ctrw-slider-controls-dots');
   const controlsContainer = container.querySelector('.ctrw-slider-controls');
  
   if (slides.length === 0) return; // Exit if no reviews

   let currentIndex = 0;
   const slideCount = slides.length;

   const getVisibleSlides = () => {
       if (window.innerWidth <= 768) return 1;
       if (window.innerWidth <= 992) return 2;
       return 3;
   };

   function updateSlider() {
       const visibleSlides = getVisibleSlides();
       const maxIndex = Math.max(0, slideCount - visibleSlides);
       const pages = maxIndex + 1;

       // Clamp currentIndex to be within valid bounds
       currentIndex = Math.max(0, Math.min(currentIndex, maxIndex));

       const slideWidth = slides.length > 0 ? slides[0].offsetWidth : 0;
       const gap = 20;
       const offset = currentIndex * (slideWidth + gap);
       slidesContainer.style.transform = `translateX(-${offset}px)`;

       // Dynamically create and update dots
       if (dotsContainer) {
           dotsContainer.innerHTML = ''; // Clear existing dots
           if (pages > 1) { // Only show dots if there's more than one page
               for (let i = 0; i < pages; i++) {
                   const dot = document.createElement('button');
                   dot.classList.add('ctrw-slider-dot');
                   if (i === currentIndex) {
                       dot.classList.add('ctrw-slider-active');
                   }
                   dot.dataset.index = i;
                   dot.setAttribute('aria-label', `Go to slide ${i + 1}`);
                   dot.addEventListener('click', () => {
                       currentIndex = i;
                       updateSlider();
                   });
                   dotsContainer.appendChild(dot);
               }
           }
       }

       // Update button states
       if (prevButton) prevButton.disabled = currentIndex === 0;
       if (nextButton) nextButton.disabled = currentIndex === maxIndex;

       // Hide controls if all slides are visible
       const controlsVisible = slideCount > visibleSlides;
       if (controlsContainer) {
           controlsContainer.style.display = controlsVisible ? 'flex' : 'none';
       }
       slidesContainer.classList.toggle('center-items', !controlsVisible);
   }
  
   // "Read More" functionality
   slides.forEach(slide => {
       const content = slide.querySelector('.ctrw-slider-content');
       if (content.scrollHeight > content.clientHeight) {
           const readMoreBtn = document.createElement('button');
           readMoreBtn.textContent = 'Read more';
           readMoreBtn.className = 'ctrw-read-more';
           slide.appendChild(readMoreBtn);

           readMoreBtn.addEventListener('click', () => {
               content.classList.toggle('expanded');
               readMoreBtn.textContent = content.classList.contains('expanded') ? 'Read less' : 'Read more';
           });
       }
   });

   // Event Listeners
   if (nextButton) {
       nextButton.addEventListener('click', () => {
           currentIndex++;
           updateSlider();
       });
   }

   if (prevButton) {
       prevButton.addEventListener('click', () => {
           currentIndex--;
           updateSlider();
       });
   }

   window.addEventListener('resize', updateSlider);

   // Initial setup
   updateSlider();
});
</script>


