<?php
/**
* Customer Reviews Slider Template
*
* This template displays customer reviews in a responsive, stylish slider.
*
* @package ctrw
*/

if (!defined('ABSPATH')) {
   exit; // Exit if accessed directly.
}

// Fetch approved reviews from the database model.
$reviews_model = new CTRW_Model();
$reviews = $reviews_model->get_reviews('approved');

// Get plugin settings to determine how many reviews to show.
$settings = get_option('customer_reviews_settings', []);
$reviews_per_page = $settings['reviews_per_page'] ?? 10;
$reviews = array_slice($reviews, 0, $reviews_per_page);
$review_count = count($reviews);
?>
<div class="ctrw-slider-container">


   <div class="ctrw-slider-navigation-wrapper">
       <div class="ctrw-slider-wrapper">
           <div class="ctrw-slider-slides <?php if ($review_count < 3) echo 'center-items'; ?>">
               <?php
               foreach ($reviews as $review) {
                   // Settings for each review
                   $show_city = !empty($settings['show_city']);
                   $date_format_setting = $settings['date_format'] ?? 'MM/DD/YYYY';
                   $formatted_date = '';
                   if (!empty($review->created_at)) {
                       $timestamp = strtotime($review->created_at);
                       $date_format = str_replace(['MM', 'DD', 'YYYY'], ['m', 'd', 'Y'], $date_format_setting);
                       $formatted_date = date($date_format, $timestamp);
                   }
               ?>
               <div class="ctrw-slider-slide">
                   <div class="ctrw-slider-meta">
                  
                       <div class="ctrw-slider-author-info">
                           <div class="ctrw-slider-author-name"><?= esc_html($review->name); ?></div>
                           <div class="ctrw-slider-date"><?= esc_html($formatted_date); ?></div>
                          

                       </div>
                   </div>
                  
                   <div class="ctrw-slider-rating-wrapper">
                       <div class="ctrw-slider-rating" aria-label="Rating: <?php echo (int) $review->rating; ?> out of 5 stars">
                           <?php for ($i = 0; $i < 5; $i++) : ?>
                               <span class="<?php echo $i < $review->rating ? 'filled' : 'empty'; ?>">&#9733;</span>
                           <?php endfor; ?>
                       </div>
                       <svg class="ctrw-verified-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1.41 14.59L6.17 13.17l1.41-1.41L10.59 14.17l5.83-5.83 1.41 1.41-7.24 7.24z"></path></svg>
                   </div>
                  
                   <div class="ctrw-slider-content">
                      <div class="ctrw-review-title"><?= esc_html($review->title); ?></div>
                       <p><?= esc_html($review->comment); ?></p>
                   </div>
               </div>
               <?php } ?>
           </div>
       </div>
   </div>

   <?php if ($review_count > 1): ?>
   <div class="ctrw-slider-controls">
       <button class="ctrw-slider-prev" aria-label="Previous review">&#10094;</button>
       <div class="ctrw-slider-controls-dots">
           <!-- Dots are dynamically generated by JavaScript -->
       </div>
       <button class="ctrw-slider-next" aria-label="Next review">&#10095;</button>
   </div>
   <?php endif; ?>
</div>
